name: test-workflow
on:
  push:

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start test and build
      - run: echo "Starting test/build job ..."
        
      - name: Download project inside runner
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Run tests and build
        run: mvn clean install